### ISSUE TITLE
Skip initialization on unsupported models

### ISSUE THREAD

**Issue by spongemak** [mtflud/homebridge-cuby#1]
Since version 1.0.10 I got this error, Skip initialization on unsupported models.

**Comment by mtflud** [comment]
> Since version 1.0.10 I got this error, Skip initialization on unsupported models.

Do you know which device models you're using? I limited the plugin to only work with Cuby G4 devices because I don't own any other models, and I don't know if it would work correctly on them. If you can confirm it works on other models I can add them no problem!

**Comment by spongemak** [comment]
I have two Cuby G3 devices, working fine with version 1.0.9, thanks.

**Comment by mtflud** [comment]
@spongemak I just published version `1.0.12` adding G3 as supported devices. Please let me know if that fixes the issue. Thanks for reporting!

**Comment by spongemak** [comment]
Hi, I still getting an error 

[18/09/2022, 16:42:33] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:33] [Cuby] Skipping device initialization for device: Clima Luisito
[18/09/2022, 16:42:33] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:33] [Cuby] Skipping device initialization for device: Clima Dormitorio
[18/09/2022, 16:42:33] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:33] [Cuby] Skipping device initialization for device: Clima Luisito
[18/09/2022, 16:42:33] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Dormitorio
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Luisito
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Dormitorio
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Luisito
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Dormitorio
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Luisito
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200
[18/09/2022, 16:42:34] [Cuby] Skipping device initialization for device: Clima Dormitorio
[18/09/2022, 16:42:34] [Cuby] Cannot confirm if device is supported. Please open an issue if you think this is an error. Model is: 200

it goes endless, thanks.

**Comment by mtflud** [comment]
@spongemak Ah! I had the incorrect model added. Thanks for providing me with the logs, it should now work fine with version `1.0.13`, but let me know if it doesn't. Thanks!

**Comment by spongemak** [comment]
It's working now, thanks!
